# Default values for livingroom.cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# helm upgrade --install livingroom-cloud . \
# --namespace livingroom-cloud \
# --create-namespace \
# -f values.yaml 
# Create image pull secret in namespace 
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=vekjja \
#   --docker-password=$GITHUB_PAT \
#   -n livingroom-cloud

# Bitnami PostgreSQL subchart (https://github.com/bitnami/charts/tree/main/bitnami/postgresql).
postgresql:
  enabled: true
  fullnameOverride: livingroom-cloud-psql

  image:
    pullPolicy: IfNotPresent
    debug: true

  auth:
    postgresPassword: postgres
    database: livingroom-cloud

  volumePermissions:
    enabled: true

  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: local-path

    resourcesPreset: none
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

image:
  repository: ghcr.io/vekjja/livingroom.cloud
  pullPolicy: Always
  tag: "v0.3.0"

imagePullSecrets:
- name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

# This section builds out the srvice account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {} # fsGroup: 2000

securityContext: {}
  # capabilities:
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

externalSecret:
  enabled: true
  name: livingroom-cloud-env
  secretStoreName: gcp-secret-manager
  secretStoreKind: ClusterSecretStore
  remoteSecretName: livingroom-cloud
  refreshInterval: 1h

envFrom:
- secretRef:
    name: livingroom-cloud-env

env:
- name: DATABASE_URL
  value: 
- name: NODE_ENV
  value: production

ingress:
  enabled: true
  className: "nginx"
  annotations: { cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-production" }
  hosts:
  - host: livingroom.cloud
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: livingroom.cloud-tls
    hosts:
    - livingroom.cloud

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 18
  periodSeconds: 10
  failureThreshold: 30

startupProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 9
  periodSeconds: 10
  failureThreshold: 30

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
